import { getProducts, getScrape } from "./APIaccessor.js";

window.onload = function () {
    Main();
}

async function Main() {
    // const products = (await getProducts()).body;
    // const scraped = (await getScrape()).body;
    const products = JSON.parse(`[{"ID":1,"name":"あんぽ柿","summary":"品種は平核無柿、蜂屋柿など","desc":null,"product_categories_ID":1,"yen_per_kg":78,"kg_per_1a":240},{"ID":2,"name":"いちご","summary":"品種はとちおとめ、さちのか、など","desc":null,"product_categories_ID":2,"yen_per_kg":218,"kg_per_1a":1190},{"ID":3,"name":"いんげん","summary":"品種はいちず、鴨川グリーンなど","desc":null,"product_categories_ID":2,"yen_per_kg":72,"kg_per_1a":8678},{"ID":4,"name":"きゅうり","summary":"品種はアンコール10、パイロット2号、南極1号など","desc":null,"product_categories_ID":2,"yen_per_kg":580,"kg_per_1a":233},{"ID":5,"name":"さくらんぼ","summary":"品種は佐藤錦など","desc":null,"product_categories_ID":1,"yen_per_kg":2835,"kg_per_1a":40},{"ID":6,"name":"さやえんどう","summary":"品種は姫みどり、ゆうさやなど","desc":null,"product_categories_ID":2,"yen_per_kg":43,"kg_per_1a":1157},{"ID":7,"name":"しいたけ","summary":null,"desc":null,"product_categories_ID":3,"yen_per_kg":822,"kg_per_1a":928},{"ID":8,"name":"春菊","summary":null,"desc":null,"product_categories_ID":2,"yen_per_kg":119,"kg_per_1a":516},{"ID":9,"name":"西洋なし","summary":"品種はラ・フランス、ル・レクチェ、ゼネラル・レクラークなど","desc":null,"product_categories_ID":1,"yen_per_kg":157,"kg_per_1a":373},{"ID":10,"name":"ニラ","summary":"品種はワンダーグリーン、パワフルグリーンベルトなど","desc":null,"product_categories_ID":2,"yen_per_kg":168,"kg_per_1a":546},{"ID":11,"name":"花わさび","summary":null,"desc":null,"product_categories_ID":2,"yen_per_kg":3039,"kg_per_1a":6000},{"ID":12,"name":"ピーマン","summary":null,"desc":null,"product_categories_ID":2,"yen_per_kg":346,"kg_per_1a":346},{"ID":13,"name":"ぶどう","summary":"品種は巨峰、高尾など","desc":null,"product_categories_ID":1,"yen_per_kg":94,"kg_per_1a":1062},{"ID":14,"name":"桃","summary":"品種はあかつき、川中島白桃、ゆうぞらなど","desc":null,"product_categories_ID":1,"yen_per_kg":158,"kg_per_1a":695},{"ID":15,"name":"りんご","summary":"品種は王林、ふじなど","desc":null,"product_categories_ID":1,"yen_per_kg":159,"kg_per_1a":287}]`);
    const scraped = JSON.parse(`[{"id":"strawberry_f","price":4410},{"id":"strawberry","price":2364.59},{"id":"cucumber_f","price":1797.22},{"id":"cucumber","price":539},{"id":"greenbeans","price":256},{"id":"Snowpeas","price":2268.33},{"id":"westernpear_f","price":4410},{"id":"Shungiku","price":319},{"id":"westernpear","price":2798},{"id":"Chinesechive","price":1113.18},{"id":"persimmon","price":7747.09},{"id":"greenpepper","price":1278.1},{"id":"grapes","price":4740},{"id":"Shiitake","price":1467},{"id":"peach","price":3515},{"id":"apple","price":2741},{"id":"Snowpeas_f","price":1849.96},{"id":"persimmon_f","price":3639.57},{"id":"greenbeans_f","price":1963.64},{"id":"Shungiku_f","price":4678.02},{"id":"grapes_f","price":5610.02},{"id":"flowerwasabi","price":3047.29},{"id":"Chinesechive_f","price":2992.64},{"id":"greenpepper_f","price":1678.38},{"id":"peach_f","price":9782.85},{"id":"apple_f","price":2080.24}]`)
    console.log(products);
    console.log(scraped);
}
