DATABASE_TABLE_ADMINS = "admins"
DATABASE_TABLE_CONTACTS = "contacts"
DATABASE_TABLE_FORM = "form"
DATABASE_TABLE_PRODUCTS = "products"
DATABASE_TABLE_PRODUCTCATEGORIES = "product_categories"
DATABASE_TABLES = [
    DATABASE_TABLE_ADMINS,
    DATABASE_TABLE_CONTACTS,
    DATABASE_TABLE_FORM,
    DATABASE_TABLE_PRODUCTS,
    DATABASE_TABLE_PRODUCTCATEGORIES,
]
